# Generated by Django 3.0.9 on 2020-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jati', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengalaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerita_pengalaman', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Kegiatan',
        ),
    ]
