# Generated by Django 3.0.9 on 2020-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='static/francis/img/no-image.png', upload_to=''),
        ),
    ]
